markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

exclude:
  - scripts

collections:
  docs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "_docs"
    values:
      layout: "document"
